apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    safe.k8s.fmeserver.component: data
    {{- include "fmeserver.common.labels" . | indent 4 }}
  name: fmeserver-data
spec:
  {{- with .Values.storage }}
  accessModes:
  - {{ .fmeserver.accessMode }}
  {{- if and (not .useHostDir) .fmeserver.class }}
  storageClassName: {{ .fmeserver.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .fmeserver.size }}
  {{- end }}
