{{- if not (empty $.Values.fmeserver.engines.awsServiceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "fme-engine-aws"
  labels:
    safe.k8s.fmeserver.component: engine
    {{- include "fmeserver.common.labels" $ | indent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.fmeserver.engines.awsServiceAccount.iamRoleArn }}
{{- end }}
