{{- if not .Values.fmeserver.database.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fmeserver.fullname" . }}
  labels:
    {{- include "fmeserver.common.labels" . | indent 4 }}
type: Opaque
data:
  fmeserver-db-password: {{ .Values.fmeserver.database.password | b64enc | quote }}
{{- end -}}
